# =====================================================================
#  generate-secrets.ps1
#  Generate strong secrets for the Strapi + Postgres + pgAdmin stack.
#  Output: ready-to-use .env.generated  (rename to .env to use)
#
#  USAGE:
#    powershell -ExecutionPolicy Bypass -File .\generate-secrets.ps1
#    powershell -ExecutionPolicy Bypass -File .\generate-secrets.ps1 -Length 48
# =====================================================================
[CmdletBinding()]
param(
    [ValidateRange(32, 128)]
    [int]$Length = 40
)

$ErrorActionPreference = 'Stop'

# charset safe for .env parser: no # $ ' " spaces
$Alnum = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'
$Sym   = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@%^&*()_+-=?.~'

function New-RandomString {
    param(
        [int]$Len,
        [string]$Alpha
    )
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()
    try {
        $out = [char[]]::new($Len)
        for ($i = 0; $i -lt $Len; $i++) {
            $b = [byte[]]::new(1)
            $rng.GetBytes($b)
            $out[$i] = $Alpha[$b[0] % $Alpha.Length]
        }
        return (-join $out)
    } finally {
        $rng.Dispose()
    }
}

# Strapi v4: APP_KEYS = comma-separated base64 of 4 keys
$appKeys = ((0..3 | ForEach-Object {
    $k = New-RandomString -Len $Length -Alpha $Alnum
    [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($k))
}) -join ',')

$secrets = [ordered]@{
    APP_KEYS            = $appKeys
    JWT_SECRET          = New-RandomString -Len $Length -Alpha $Alnum
    API_TOKEN_SALT      = New-RandomString -Len $Length -Alpha $Alnum
    TRANSFER_TOKEN_SALT = New-RandomString -Len $Length -Alpha $Alnum
    DB_PASSWORD         = New-RandomString -Len $Length -Alpha $Sym
    PGADMIN_PASSWORD    = New-RandomString -Len $Length -Alpha $Sym
    EMAIL_APP_PASSWORD  = New-RandomString -Len $Length -Alpha $Sym
}

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('# --- auto-generated by generate-secrets.ps1 ---')
[void]$out.AppendLine(([string]::Format('#   generated: {0:yyyy-MM-dd HH:mm:ss}', (Get-Date))))
[void]$out.AppendLine()
[void]$out.AppendLine('# --- Postgres / database ---')
[void]$out.AppendLine('DATABASE_USER=poonsak')
[void]$out.AppendLine('DATABASE_DB=poonsak')
[void]$out.AppendLine('DATABASE_CLIENT=postgres')
[void]$out.AppendLine('DATABASE_HOST=db')
[void]$out.AppendLine('DATABASE_PORT=5432')
[void]$out.AppendLine('DB_PASSWORD={0}' -f $secrets.DB_PASSWORD)
[void]$out.AppendLine()
[void]$out.AppendLine('# --- pgAdmin UI  http://localhost:8083 ---')
[void]$out.AppendLine('DATABASE_EMAIL=poonsak-p@rmutp.ac.th')
[void]$out.AppendLine('PGADMIN_PASSWORD={0}' -f $secrets.PGADMIN_PASSWORD)
[void]$out.AppendLine()
[void]$out.AppendLine('# --- Strapi JWT / tokens ---')
[void]$out.AppendLine('APP_KEYS={0}' -f $secrets.APP_KEYS)
[void]$out.AppendLine('JWT_SECRET={0}' -f $secrets.JWT_SECRET)
[void]$out.AppendLine('API_TOKEN_SALT={0}' -f $secrets.API_TOKEN_SALT)
[void]$out.AppendLine('TRANSFER_TOKEN_SALT={0}' -f $secrets.TRANSFER_TOKEN_SALT)
[void]$out.AppendLine()
[void]$out.AppendLine('# --- email app password (create at Google/MS account) ---')
[void]$out.AppendLine('EMAIL_APP_PASSWORD={0}' -f $secrets.EMAIL_APP_PASSWORD)
[void]$out.AppendLine()
[void]$out.AppendLine('# --- host bound ports ---')
[void]$out.AppendLine('DB_PORT=54327')
[void]$out.AppendLine('ADMIN_PORT=8083')
[void]$out.AppendLine('APP_PORT=9093')

$target = Join-Path $PSScriptRoot '.env.generated'
Set-Content -LiteralPath $target -Value $out.ToString() -Encoding utf8

Write-Host "[OK] Created: $target" -ForegroundColor Green
Write-Host ''
Write-Host '  Apply with:' -ForegroundColor Cyan
Write-Host '    Remove-Item .env; Rename-Item .env.generated .env'
Write-Host '    docker compose down'
Write-Host '    docker compose up -d --build'
Write-Host ''
Write-Host '  IMPORTANT:' -ForegroundColor Yellow
Write-Host '    Postgres keeps the OLD password inside the data volume.'
Write-Host '    Reset it, or drop the volume:'
Write-Host "      docker compose exec db psql -U poonsak -d poonsak -c ""ALTER USER poonsak WITH PASSWORD '<NEW_DB_PASSWORD>';"""
Write-Host '      or:  docker compose down -v   (wipes database data!)'
Write-Host '    Strapi: new JWT_SECRET/APP_KEYS = every admin must re-login.'